dist: trusty
sudo: false

language: haskell

env:
  - GHCVER=7.8

cache: apt

addons:
  apt:
    packages:
      - fonts-linuxlibertine
      - librsvg2-bin
      - lmodern
      - make
      - texlive
      - texlive-fonts-extra
      - texlive-fonts-recommended
      - texlive-generic-recommended
      - texlive-latex-extra
      - texlive-xetex

before_install:
  - wget https://github.com/Ranks/emojione/archive/v2.2.7.tar.gz
  - tar xzf v2.2.7.tar.gz
  - wget https://raw.githubusercontent.com/mreq/xelatex-emoji/master/xelatexemoji.sty
  - wget https://raw.githubusercontent.com/mreq/xelatex-emoji/master/xelatexemoji-flags.sty
  - sed -i 's/^\(\\usepackage{amsmath}\)/%\1/' xelatexemoji.sty
  - sed -i 's/^\(\\providecommand{\\xelatexemojipath}\)/%\1/' xelatexemoji.sty

install:
  - cabal install pandoc pandoc-citeproc
  - export PATH=$HOME/.cabal/bin:$PATH

script:
  - LANGUAGE= make ${ACTION}

after_success:
  - >
    test "${ACTION}" = "slides" \
      && test "${TRAVIS_PULL_REQUEST}" = "false" \
      && test "${TRAVIS_BRANCH}" = "master" \
      && bash deploy.sh \
      || echo ":-)"
