language:
  c

cache: apt

addons:
  apt:
    packages:
      - fonts-inconsolata
      - fonts-linuxlibertine
      - lmodern
      - make
      - pandoc
      - texlive
      - texlive-fonts-extra
      - texlive-fonts-recommended
      - texlive-xetex

env:
  - ACTION=slides
  - ACTION=pdfs

script:
  - make ${ACTION}
