language:
  c

cache: apt

addons:
  apt:
    packages:
      - fonts-linuxlibertine
      - lmodern
      - make
      - pandoc
      - texlive
      - texlive-fonts-extra
      - texlive-fonts-recommended
      - texlive-generic-recommended
      - texlive-latex-extra
      - texlive-xetex

env:
  - ACTION=slides
  - ACTION=pdfs book

script:
  - LANGUAGE= make ${ACTION}
