dist: trusty
sudo: false

language: haskell

cache: apt

env:
  global:
    - GHCVER=7.8
    - BUILD_FOLDER=build
    - BUILD_BRANCH=test
    - ON_PR=false
  matrix:
    - ACTION=slides
    - ACTION=pdfs
    - ACTION=book

addons:
  apt:
    packages:
      - fonts-linuxlibertine
      - librsvg2-bin
      - lmodern
      - make
      - texlive
      - texlive-fonts-extra
      - texlive-fonts-recommended
      - texlive-generic-recommended
      - texlive-latex-extra
      - texlive-xetex

before_install:
  - wget https://github.com/Ranks/emojione/archive/v2.2.7.tar.gz
  - tar xzf v2.2.7.tar.gz
  - wget https://raw.githubusercontent.com/mreq/xelatex-emoji/master/xelatexemoji.sty
  - wget https://raw.githubusercontent.com/mreq/xelatex-emoji/master/xelatexemoji-flags.sty
  - sed -i 's/^\(\\usepackage{amsmath}\)/%\1/' xelatexemoji.sty
  - sed -i 's/^\(\\providecommand{\\xelatexemojipath}\)/%\1/' xelatexemoji.sty
  - >
    test "${TRAVIS_PULL_REQUEST}" = "${ON_PR}" \
      && test "${TRAVIS_BRANCH}" = "${BUILD_BRANCH}" \
      && chmod a+x gitInit.sh \
      && ./gitInit.sh "${BUILD_FOLDER}" gh-pages \
      || echo ":-)"

install:
  - cabal install pandoc pandoc-citeproc
  - export PATH=$HOME/.cabal/bin:$PATH

script:
  - LANGUAGE= make ${ACTION}

after_success:
  - >
    test "${TRAVIS_PULL_REQUEST}" = "${ON_PR}" \
      && test "${TRAVIS_BRANCH}" = "${BUILD_BRANCH}" \
      && bash deploy.sh "${BUILD_FOLDER}" \
      || echo ":-)"
